name: CI
on:
  push:
    branches:
      - live
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: daniel-cotton/puppeteer-container@master
        with:
          args: pnpm install
      - name: Test
        uses: daniel-cotton/puppeteer-container@master
        with:
          args: pnpm test